services:
    sonata.admin.categorie:
        class: Annuaire\FootBundle\Admin\CategorieAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Categorie" }
        arguments:
            - ~
            - Annuaire\FootBundle\Entity\Categorie
            - ~
        calls:
            - [ setTranslationDomain, [AnnuaireFootBundle]]

    sonata.admin.terrain:
        class: Annuaire\FootBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Terrain" }
        arguments:
            - ~
            - Annuaire\FootBundle\Entity\Terrain
            - ~
        calls:
            - [ setTranslationDomain, [AnnuaireFootBundle]]