parameters:
#    annuaire_foot.example.class: Annuaire\FootBundle\Example

services:
#    annuaire_foot.example:
#        class: %annuaire_foot.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
